version: '2.1'
services:
  djangoapp:
    container_name: djangoapp
    image: djangoapp
    environment: 
      - DJANGO_SECRET_KEY=KEY_HERE
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=YOUR_HOST
    volumes:
      - ./app:/opt/services/djangoapp/src
    ports:
      - 8000:8000
